services:
  dev:
    profiles: ["dev"]
    build:
      context: ../../
      dockerfile: services/naurffxiv/Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app/services/naurffxiv
      - /app/services/naurffxiv/node_modules
      - /app/services/naurffxiv/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    env_file:
      - path: .env
        required: false
      - path: .env.local
        required: false

  prod:
    profiles: ["prod"]
    build:
      context: ../../
      dockerfile: services/naurffxiv/Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - path: .env
        required: false
      - path: .env.local
        required: false
