# .NET service configuration
orphan: true
repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        entry: dotnet format Authingway.csproj --verify-no-changes
        language: system
        files: \.(cs|vb)$
        pass_filenames: false
        priority: 0
