# Python service configuration
orphan: true
repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        priority: 1
      - id: ruff-format
        priority: 0

  - repo: https://foundry.fsky.io/vel/ty-pre-commit
    rev: 0.0.11
    hooks:
      - id: ty-check
        args: [--python=venv/]
